services:
  app:
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    build: ./database/
    healthcheck:
      test: ["CMD","pg_isready","-U","postgres"]
      interval: 5s
      retries: 5
    restart: always