services:
  db:
    build: ./database/
    ports:
      - 5435:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init_scripts/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD","pg_isready","-U","postgres"]
      interval: 10s
      retries: 10
    restart: always
  app:
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
